language: node_js

node_js:
  - 10
dist: trusty
branches:
  only:
    - master
addons:
  chrome: stable
cache:
  directories:
    - $HOME/.npm
before_install:
  - npm i -g @angular/cli@7.0.5
  - npm install codecov -g
install:
  - npm rebuild node-sass
  - npm ci
script:
  - npm run ci
  - cp README.md LICENSE dist/mat-advanced-table
after_success:
  - codecov
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release

notifications:
  email: false
